version: '2'
services:
    scraper-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/scraper/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=scraper
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
